# Changes here will be overwritten by Copier
# !!!!! DO NOT MANUALLY MODIFY THIS FILE !!!!!
_commit: v1.0.3
_src_path: https://github.com/modelblocks-org/data-module-template.git
authors:
-   email: m.chen-4@tudelft.nl
    family_name: Chen
    given_name: Meijun
github_org: tud-mchen6
license: Apache-2.0
maintainers:
-   email: m.chen-4@tudelft.nl
    family_name: Chen
    given_name: Meijun
module_code_name: module_gh2_prod
module_description: Given a cost curve for variable renewable technologies production
    in energy terms, water availability, and cost assumption for electrolysers, this
    module helps calculate the green hydrogen production curve.
module_human_name: Module for green hydrogen production calculation
