$schema: "https://json-schema.org/draft/2020-12/schema"
description: "Schema for user-provided configuration files."
type: object
additionalProperties: false
properties:
  electrolyser_type:
    description: type of electrolyser, AE or PEM
    type: string
  discount_rate:
    description: discount rate for calculation
    type: number
  

  # overrides:
  #   type: object
  #   additionalProperties:
  #     type: object
  #     energy_per_kg:
  #       type: number
  #     electrolyser_cost:
  #       type: number
  #     water_need_override: 
  #       type: number